#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

bspc monitor DP-1 -d 1 2 3 4 5
bspc monitor DP-2 -d 6 7 8 9 0

bspc config border_width         3
bspc config window_gap           0

bspc config split_ratio          0.5011
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

# Border
bspc config focused_border_color        "#ff0000"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
/usr/lib/polkit-kde-authentication-agent-1 &
# Notifications
/usr/bin/dunst &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
# picom -b &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh &

feh --bg-scale ~/Documents/wallpaper.jpg &

wmname LG3D &
export XDG_CURRENT_DESKTOP=KDE &
export XDG_SESSION_DESKTOP=KDE &
export SAL_USE_VCLPLUGIN=kde5 &
